# GitHub Actions build matrix for Charybdis (modern-zmk-config)
# Builds firmware for nice!nano v2 controllers

include:
  - board: nice_nano_v2
    shield: charybdis_left
    # Left/peripheral: Studio disabled to save RAM/FLASH
    cmake-args:
      - DCONFIG_ZMK_STUDIO=n
  - board: nice_nano_v2
    shield: charybdis_right
    # Right/central: Studio enabled + USB/UART RPC endpoint
    snippet: studio-rpc-usb-uart
    cmake-args:
      - DCONFIG_ZMK_STUDIO=y
      - DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: settings_reset
